"""add discount to grocery trip items

Revision ID: 44b7e2ec32e8
Revises: 
Create Date: 2026-03-16 23:21:10.048807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b7e2ec32e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_food_data_canonical_name', table_name='food_data')
    op.drop_index('ix_food_data_category', table_name='food_data')
    op.drop_index('ix_food_data_display_name', table_name='food_data')
    op.drop_index('ix_food_data_display_name_de', table_name='food_data')
    op.drop_index('ix_food_data_fdc_id', table_name='food_data')
    op.drop_table('food_data')
    op.add_column('grocery_trip_items', sa.Column('discount', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grocery_trip_items', 'discount')
    op.create_table('food_data',
    sa.Column('api_food_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('canonical_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_fast_food', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('calories_kcal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('protein_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sugars_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fiber_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('saturated_fat_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sodium_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cholesterol_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'usda'::character varying"), autoincrement=False, nullable=False),
    sa.Column('fdc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('display_name_de', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('api_food_id', name='food_data_pkey')
    )
    op.create_index('ix_food_data_fdc_id', 'food_data', ['fdc_id'], unique=True)
    op.create_index('ix_food_data_display_name_de', 'food_data', ['display_name_de'], unique=False)
    op.create_index('ix_food_data_display_name', 'food_data', ['display_name'], unique=False)
    op.create_index('ix_food_data_category', 'food_data', ['category'], unique=False)
    op.create_index('ix_food_data_canonical_name', 'food_data', ['canonical_name'], unique=False)
    # ### end Alembic commands ###
